### PR TITLE
Upgrade Metals, the Scala language server, to version 0.9.5

### PR DESCRIPTION
**Pull request by sideeffffect**
Signed-off-by: sideeffffect <ondra.pelech@gmail.com>

### CODE REVIEW

**Comment by sideeffffect** [comment]
@ericwill coud you please have a look at this, please? :pray:

**Review by ericwill — COMMENTED** [review]
The `VERSION` file needs to be bumped to `0.9.4`.

**Comment by ericwill** [comment]
Also, could you update the base image to alpine `3.12.1` (see PR #8)

**Comment by sideeffffect** [comment]
@ericwill This PR is blocked on https://github.com/scalameta/metals/issues/2156 , so you probably should merge https://github.com/che-dockerfiles/che-sidecar-scala/pull/8 yourself now

**Pull request closed without merging**
