### PR TITLE
0.9.0

### PR DESCRIPTION
**Pull request by sideeffffect**
This should go into branch `0.9.0`

### CODE REVIEW

**Comment by sideeffffect** [comment]
any idea @olafurpg @tgodzik why is `coursier launch org.scalameta:metals_2.12:0.9.0 --main scala.meta.metals.DownloadDependencies` failing with
```
Exception in thread "main" coursierapi.error.SimpleResolutionError$1: Error downloading org.scalameta:mdoc_0.24:2.1.5
  not found: /root/.ivy2/local/org.scalameta/mdoc_0.24/2.1.5/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/scalameta/mdoc_0.24/2.1.5/mdoc_0.24-2.1.5.pom
  not found: https://oss.sonatype.org/content/repositories/public/org/scalameta/mdoc_0.24/2.1.5/mdoc_0.24-2.1.5.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/mdoc_0.24/2.1.5/mdoc_0.24-2.1.5.pom
```
([see the full build log](https://github.com/che-dockerfiles/che-sidecar-scala/runs/653543961?check_suite_focus=true#step:3:1128))
There really isn't any `mdoc_0.24`, just `mdoc_2.11`, `mdoc_2.12` and `mdoc_2.13`, why is it trying to download such a weird version?

**Comment by sideeffffect** [comment]
@ericwill could you please create the `0.9.0` branch in the meantime?

**Comment by tgodzik** [comment]
@sideeffffect My bad, merged the Scala 3 support, but forgot about the downloader. Fixing it now.

**Comment by tgodzik** [comment]
https://github.com/scalameta/metals/pull/1711 - after we merge it, you should be able to just use the snapshot for the downloader

**Comment by ericwill** [comment]
> @ericwill could you please create the `0.9.0` branch in the meantime?

The version branch is based on the version of the plugin (usually). If that hasn't changed the PR can be submitted against the 1.8.6 branch.

**Comment by sideeffffect** [comment]
@ericwill yes, the version really should be `0.9.0`, because it's for version of Metals 0.9.0 (see the env variables in the Dockerfile)

**Comment by sideeffffect** [comment]
@ericwill The build is green, we can merge this (to `0.9.0` preferably) :tada:

**Comment by ericwill** [comment]
0.9.0 branch created!

**Comment by ericwill** [comment]
This one can be closed now, right?

**Comment by sideeffffect** [comment]
yep

**Pull request closed without merging**
